services:
  postgres:
    image: postgres:16
    container_name: carta-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: carta
      POSTGRES_PASSWORD: carta
      POSTGRES_DB: carta

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
